### ISSUE TITLE
Can not download the Data Fashion

### ISSUE THREAD

**Issue by haithanhp** [zhusz/ICCV17-fashionGAN#2]
Hi @zhusz ,

Thank for your interesting work. I want to download the data but I can only download **Category and Attribute Prediction Benchmark**. I can not download the rest. I see there are four datasets. Which one do you use for your algorithm? I did try both google drive and dropbox.

Thanks,
Hai

**Comment by zhusz** [comment]
Just the  Category and Attribute Prediction Benchmark one.
